### ISSUE TITLE
General Todo

### ISSUE THREAD

**Issue by mundya** [ctn-archive/nengo_spinnaker_2014#26]
- [x] Generalised IO for USB and Ethernet - with Simulator support for Nodes
- [x] Refactor Vertex code
- [x] Refactor Application input code to allow for multiple inputs with multiple filters
  - work in branch `multi-inputs`, to be completed and merged in
- [x] Debug/check splitting of Ensembles across processing cores
- [x] Recording of spike trains **REDO FOR NEW PROBE SYSTEM**
- [x] Check/debug subnetworks and subsubnetworks
- [x] Global inhibition
  - work progressing in `inhibition` - checked, merge when done
- [x] Probe decoded outputs
  - awaiting merge in #43 -- **REDO FOR NEW PROBE SYSTEM**
- [ ] Probe voltages -- _delay until later release?_
- [x] Increase flexibility for key construction (see #34)
- [x] neaten C code and naming conventions, "-" becomes "_"!
  - some of this in the `multi-inputs` refactor
